import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const perfectlyNineties = localFont({
  src: [
    {
      path: "../fonts/PerfectlyNineties-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/PerfectlyNineties-RegularItalic.ttf",
      weight: "400",
      style: "italic",
    },
  ],
  variable: "--font-perfectly-nineties",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${perfectlyNineties.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
